services:
  - type: web
    name: bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.7.16  # Chỉ định phiên bản Python 3.6.17
